NAME = MakeIt_2021
VERSION = 2021
OUTPUT = makeit
TARGET = 

# Directory for the object files
BUILD = ./build
SYSTEM_ROOT = 

# Binary directory with the compiler executable
BINARY = 

# Compiler for linking
LINKER = $(BINARY)clang++

# C compiler
CC_C = $(BINARY)clang

# C++ compiler
CC_CXX = $(BINARY)clang++

# Objective C compiler
CC_OBJC = $(BINARY)clang

INCLUDE_PATHS = -I./extern/libme/include -I./include
LIBRARY_PATHS = -L./extern/libme
LIBRARIES = -lme
FLAGS =
CFLAGS_C = $(FLAGS) $(INCLUDE_PATHS) -xc
CFLAGS_CXX = $(FLAGS) $(INCLUDE_PATHS) -xc++ -std=c++20 -g -Og --include=./include/makeit/Config.hpp
CFLAGS_OBJC = $(FLAGS) $(INCLUDE_PATHS) -xobjc
LFLAGS = $(LIBRARY_PATHS) $(LIBRARIES)
SOURCES = \
	./src/makeit/MakeIt.cpp \
	./src/makeit/Text.cpp \
	./src/makeit/Logger.cpp \
	./src/makeit/basic/Function.cpp \
	./src/makeit/basic/Variable.cpp \
	./src/makeit/basic/Project.cpp \
	./src/makeit/basic/BuildConfig.cpp \
	./src/makeit/functions/FnSetProperty.cpp \
	./src/makeit/functions/FnAddProperty.cpp \
	./src/makeit/functions/FnAddExtern.cpp \
	./src/makeit/functions/FnAddFiles.cpp \
	./src/makeit/functions/FnAddInstall.cpp \
	./src/makeit/functions/FnConfigure.cpp \
	./src/makeit/functions/FnPrint.cpp \
	./src/makeit/functions/FnProject.cpp \
	./src/makeit/functions/FnSource.cpp \
	./src/makeit/lexer/Lexer.cpp \
	./src/makeit/lexer/Token.cpp \
	./src/makeit/parser/Parser.cpp \
	./src/makeit/parser/ExprParser.cpp \
	./src/makeit/parser/FuncParser.cpp \
	./src/makeit/parser/StmtParser.cpp \
	./src/makeit/parser/VariParser.cpp \
	./src/makeit/target/GMakeTarget.cpp \
	./src/makeit/target/YCMTarget.cpp
OBJECTS = $(SOURCES:%=$(BUILD)/%.o)
DEPENDS = $(OBJECTS:%.o=%.d)
EXTERNS =

.PHONY: $(NAME)
$(NAME): $(OUTPUT) $(EXTERNS)


$(OUTPUT): $(OBJECTS)
	@$(LINKER) -o $@ $^ $(LFLAGS)


-include $(DEPENDS)

# C++ source
$(BUILD)/./src/makeit/MakeIt.cpp.o: ./src/makeit/MakeIt.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/Text.cpp.o: ./src/makeit/Text.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/Logger.cpp.o: ./src/makeit/Logger.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/basic/Function.cpp.o: ./src/makeit/basic/Function.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/basic/Variable.cpp.o: ./src/makeit/basic/Variable.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/basic/Project.cpp.o: ./src/makeit/basic/Project.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/basic/BuildConfig.cpp.o: ./src/makeit/basic/BuildConfig.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/functions/FnSetProperty.cpp.o: ./src/makeit/functions/FnSetProperty.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/functions/FnAddProperty.cpp.o: ./src/makeit/functions/FnAddProperty.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/functions/FnAddExtern.cpp.o: ./src/makeit/functions/FnAddExtern.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/functions/FnAddFiles.cpp.o: ./src/makeit/functions/FnAddFiles.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/functions/FnAddInstall.cpp.o: ./src/makeit/functions/FnAddInstall.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/functions/FnConfigure.cpp.o: ./src/makeit/functions/FnConfigure.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/functions/FnPrint.cpp.o: ./src/makeit/functions/FnPrint.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/functions/FnProject.cpp.o: ./src/makeit/functions/FnProject.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/functions/FnSource.cpp.o: ./src/makeit/functions/FnSource.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/lexer/Lexer.cpp.o: ./src/makeit/lexer/Lexer.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/lexer/Token.cpp.o: ./src/makeit/lexer/Token.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/parser/Parser.cpp.o: ./src/makeit/parser/Parser.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/parser/ExprParser.cpp.o: ./src/makeit/parser/ExprParser.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/parser/FuncParser.cpp.o: ./src/makeit/parser/FuncParser.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/parser/StmtParser.cpp.o: ./src/makeit/parser/StmtParser.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/parser/VariParser.cpp.o: ./src/makeit/parser/VariParser.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/target/GMakeTarget.cpp.o: ./src/makeit/target/GMakeTarget.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD

# C++ source
$(BUILD)/./src/makeit/target/YCMTarget.cpp.o: ./src/makeit/target/YCMTarget.cpp
	@echo "compiling source '$<'"
	@mkdir -p $(dir $@)
	@$(CC_CXX) -c -o $@ $< $(CFLAGS_CXX) -MMD



.PHONY: install
install:
	cp makeit /bin/makeit

.PHONY: clean
clean:
	rm -f $(OUTPUT) $(OBJECTS) $(DEPENDS)
